services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "7062:80"
    depends_on:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BackendUrl=http://backend:8080/api/Wifi/

  backend:
    build:
      context: ./backend
    ports:
      - "7147:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=db;Port=5432;User Id=postgres;Database=postgres;Password=147899;SSL Mode=Disable;Trust Server Certificate=true

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 147899
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata: